///-----------------------------------------------------------------------------
/// Copyright (C) 2020 The BeeTree Authors - All Rights Reserved
///
/// This file is subject to the terms and conditions defined in
/// file 'LICENSE', which is part of this source code package.
///
/// @file
///-----------------------------------------------------------------------------

#pragma once

namespace stm32f1xx
{
    ///
    /// GPIO Pin Definitions
    ///
    enum class GPIOPin
    {
        PA0 = 0x00,
        PA1,
        PA2,
        PA3,
        PA4,
        PA5,
        PA6,
        PA7,
        PA8,
        PA9,
        PA10,
        PA11,
        PA12,
        PA13,
        PA14,
        PA15,
        PB0 = 0x10,
        PB1,
        PB2,
        PB3,
        PB4,
        PB5,
        PB6,
        PB7,
        PB8,
        PB9,
        PB10,
        PB11,
        PB12,
        PB13,
        PB14,
        PB15,
        PC0 = 0x20,
        PC1,
        PC2,
        PC3,
        PC4,
        PC5,
        PC6,
        PC7,
        PC8,
        PC9,
        PC10,
        PC11,
        PC12,
        PC13,
        PC14,
        PC15,
        PD0 = 0x30,
        PD1,
        PD2,
        PD3,
        PD4,
        PD5,
        PD6,
        PD7,
        PD8,
        PD9,
        PD10,
        PD11,
        PD12,
        PD13,
        PD14,
        PD15,
        PE0 = 0x40,
        PE1,
        PE2,
        PE3,
        PE4,
        PE5,
        PE6,
        PE7,
        PE8,
        PE9,
        PE10,
        PE11,
        PE12,
        PE13,
        PE14,
        PE15,
        PF0 = 0x50,
        PF1,
        PF2,
        PF3,
        PF4,
        PF5,
        PF6,
        PF7,
        PF8,
        PF9,
        PF10,
        PF11,
        PF12,
        PF13,
        PF14,
        PF15,
        PG0 = 0x60,
        PG1,
        PG2,
        PG3,
        PG4,
        PG5,
        PG6,
        PG7,
        PG8,
        PG9,
        PG10,
        PG11,
        PG12,
        PG13,
        PG14,
        PG15
    };
}  // namespace stm32f1xx